# -*- coding: utf-8 -*-
# 
# Outsourced plotting class methods from respective parent classes
# 
# Created: 2020-05-06 13:32:40
# Last modified by: Stefan Fuertinger [stefan.fuertinger@esi-frankfurt.de]
# Last modification time: <2020-05-14 16:45:19>

import numpy as np
import os 

from syncopy.shared.errors import SPYValueError, SPYError, SPYTypeError, SPYWarning
from syncopy.shared.tools import layout_subplot_panels
from syncopy.plotting.spy_plotting import pltErrMsg, pltConfig
from syncopy import __plt__
if __plt__:
    import matplotlib.pyplot as plt

__all__ = []


def singlepanelplot(self, trials="all", channels="all", toilim=None, avg_channels=True,
               title=None, grid=None, fig=None, **kwargs):
    """
    Plot contents of :class:`~syncopy.AnalogData` objects using single-panel figure(s)
    
    Please refer to :func:`syncopy.singlepanelplot` for detailed usage information. 
    
    Examples
    --------
    Use :func:`~syncopy.tests.misc.generate_artificial_data` to create two synthetic 
    :class:`~syncopy.AnalogData` objects. 
    
    >>> from syncopy.tests.misc import generate_artificial_data
    >>> adata = generate_artificial_data(nTrials=10, nChannels=32) 
    >>> bdata = generate_artificial_data(nTrials=5, nChannels=16) 
    
    Plot an average of the first 16 channels, averaged across trials 2, 4, and 6:
    
    >>> fig = spy.singlepanelplot(adata, channels=range(16), trials=[2, 4, 6])
   
    Overlay average of latter half of channels, averaged across trials 1, 3, 5: 

    >>> fig = spy.singlepanelplot(adata, channels=range(16,32), trials=[1, 3, 5], fig=fig)
    
    Do not average channels:
    
    >>> fig = spy.singlepanelplot(adata, channels=range(16,32), trials=[1, 3, 5], avg_channels=False)
    
    Plot `adata` and `bdata` simultaneously in two separate figures:
    
    >>> fig1, fig2 = spy.singlepanelplot(adata, bdata, overlay=False)
    
    Overlay `adata` and `bdata`; use channel and trial selections that are valid 
    for both datasets:
    
    >>> fig3 = spy.singlepanelplot(adata, bdata, channels=range(16), trials=[1, 2, 3])
    
    See also
    --------
    syncopy.singlepanelplot : visualize Syncopy data objects using single-panel plots
    """

    # Abort if matplotlib is not available
    if not __plt__:
        raise SPYError(pltErrMsg.format("singlepanelplot"))
    
    # Ensure our one binary flag is actually binary
    if not isinstance(avg_channels, bool):
        raise SPYTypeError(avg_channels, varname="avg_channels", expected="bool")
    
    # Pass provided selections on to `Selector` class which performs error 
    # checking and generates required indexing arrays
    self._selection = {"trials": trials, 
                       "channels": channels, 
                       "toilim": toilim}
    
    # Ensure any optional keywords controlling plotting appearance make sense
    if title is not None:
        if not isinstance(title, str):
            raise SPYTypeError(title, varname="title", expected="str")
    if grid is not None:
        if not isinstance(grid, bool):
            raise SPYTypeError(grid, varname="grid", expected="bool")

    # Get trial/channel count ("raw" plotting constitutes a special case)
    if trials is None:
        nTrials = 0
        if toilim is not None:
            lgl = "`trials` to be not `None` to perform timing selection"
            act = "`toilim` was provided but `trials` is `None`"
            raise SPYValueError(legal=lgl, varname="trials/toilim", actual=act)
    else:    
        trList = self._selection.trials
        nTrials = len(trList)
    chArr = self.channel[self._selection.channel]
    nChan = chArr.size
    
    # If we're overlaying a multi-channel plot, ensure settings match up; also, 
    # do not try to overlay on top of multi-panel plots
    if hasattr(fig, "nTrialPanels") or hasattr(fig, "nChanPanels"):
        lgl = "single-panel figure generated by `singgleplot`"
        act = "multi-panel figure generated by `multipanelplot`"
        raise SPYValueError(legal=lgl, varname="fig", actual=act)
    if hasattr(fig, "chanOffsets"):
        if avg_channels:
            lgl = "multi-channel plot"
            act = "channel averaging was requested for multi-channel plot overlay"
            raise SPYValueError(legal=lgl, varname="channels/avg_channels", actual=act)
        if nChan != len(fig.chanOffsets):
            lgl = "channel-count matching existing multi-channel panels in figure"
            act = "{} channels per panel but {} channels for plotting".format(len(fig.chanOffsets), 
                                                                              nChan)
            raise SPYValueError(legal=lgl, varname="channels/channels per panel", actual=act)
    
    # Prepare indexing list respecting potential non-default `dimord`s
    idx = [slice(None), slice(None)]
    chanIdx = self.dimord.index("channel")
    timeIdx = self.dimord.index("time")
    idx[chanIdx] = self._selection.channel

    # Ensure provided timing selection can actually be averaged (leverage 
    # the fact that `toilim` selections exclusively generate slices)
    if nTrials > 0:
        tLengths = np.zeros((nTrials,), dtype=np.intp)
        for k, tsel in enumerate(self._selection.time):
            start, stop = tsel.start, tsel.stop
            if start is None:
                start = 0
            if stop is None:
                stop = self._get_time([trList[k]], 
                                       toilim=[-np.inf, np.inf])[0].stop
            tLengths[k] = stop - start
        if np.unique(tLengths).size > 1:
            lgl = "time-selections of equal length for averaging"
            act = "time-selections of varying length"
            raise SPYValueError(legal=lgl, varname="toilim/avg_trials", actual=act)

    # Generic titles for figures
    overlayTitle = "Overlay of {} datasets"

    # Either create new figure or fetch existing
    if fig is None:
        fig, ax = plt.subplots(1, tight_layout=True, squeeze=True,
                               figsize=pltConfig["singleFigSize"])
        if nTrials > 0:
            xLabel = "time [s]"
        else:
            xLabel = "samples"
        ax.set_xlabel(xLabel, size=pltConfig["singleLabelSize"])            
        ax.tick_params(axis="both", labelsize=pltConfig["singleTickSize"])
        ax.autoscale(enable=True, axis="x", tight=True)
        fig.objCount = 0
    else:
        ax, = fig.get_axes()        

    # Single-channel panel        
    if avg_channels:
        
        # Set up pieces of generic figure titles
        if nChan > 1:
            chanTitle = "Average of {} channels".format(nChan)
        else:
            chanTitle = chArr[0]
        
        # Plot entire timecourse
        if nTrials == 0:
            
            # Do not fetch entire dataset at once, but channel by channel
            chanSec = np.arange(self.channel.size)[self._selection.channel]
            pltArr = np.zeros((self.data.shape[timeIdx],), dtype=self.data.dtype)
            for chan in chanSec:
                idx[chanIdx] = chan
                pltArr += self.data[tuple(idx)].squeeze()
            pltArr /= nChan
            
            # The actual plotting command...
            ax.plot(pltArr)
            if grid is not None:
                ax.grid(grid)
            
            # Set plot title depending on dataset overlay
            if fig.objCount == 0:
                if title is None:
                    title = chanTitle
                ax.set_title(title, size=pltConfig["singleTitleSize"])
            else:
                handles, labels = ax.get_legend_handles_labels()
                ax.legend(handles, labels)
                if title is None:
                    title = overlayTitle.format(len(handles))
                ax.set_title(title, size=pltConfig["singleTitleSize"])
                
        # Average across trials
        else:
        
            # Compute channel-/trial-average time-course: 2D array with slice/list
            # selection does not require fancy indexing - no need to check this here
            pltArr = np.zeros((tLengths[0],), dtype=self.data.dtype)
            for k, trlno in enumerate(trList):
                idx[timeIdx] = self._selection.time[k]
                pltArr += self._get_trial(trlno)[tuple(idx)].mean(axis=chanIdx).squeeze()
            pltArr /= nTrials
            
            # The actual plotting command is literally one line...
            time = self.time[trList[0]][self._selection.time[0]]
            ax.plot(time, pltArr, label=os.path.basename(self.filename))
            ax.set_xlim([time[0], time[-1]])
            if grid is not None:
                ax.grid(grid)
        
            # Set plot title depending on dataset overlay
            if fig.objCount == 0:
                if title is None:
                    if nTrials > 1:
                        trTitle = "{0}across {1} trials".format("averaged " if nChan == 1 else "",
                                                                nTrials)
                    else:
                        trTitle = "Trial #{}".format(trList[0])
                    title = "{}, {}".format(chanTitle, trTitle)
                ax.set_title(title, size=pltConfig["singleTitleSize"])
            else:
                handles, labels = ax.get_legend_handles_labels()
                ax.legend(handles, labels)
                if title is None:
                    title = overlayTitle.format(len(handles))
                ax.set_title(title, size=pltConfig["singleTitleSize"])
    
    # Multi-channel panel
    else:

        # "Raw" data, do not respect any trials
        if nTrials == 0:
        
            # If required, compute max amplitude across provided channels
            if not hasattr(fig, "chanOffsets"):
                maxAmps = np.zeros((nChan,), dtype=self.data.dtype)
                tickOffsets = maxAmps.copy()
                chanSec = np.arange(self.channel.size)[self._selection.channel]
                for k, chan in enumerate(chanSec):
                    idx[chanIdx] = chan
                    pltArr = np.abs(self.data[tuple(idx)].squeeze())
                    maxAmps[k] = pltArr.max()
                    tickOffsets[k] = pltArr.mean()
                fig.chanOffsets = np.cumsum([0] + [maxAmps.max()] * (nChan - 1))
                fig.tickOffsets = fig.chanOffsets + tickOffsets.mean()

            # Do not plot all at once but cycle through channels to not overflow memory            
            for k, chan in enumerate(chanSec):
                idx[chanIdx] = chan
                ax.plot(self.data[tuple(idx)].squeeze() + fig.chanOffsets[k],
                        color=plt.rcParams["axes.prop_cycle"].by_key()["color"][fig.objCount],
                        label=os.path.basename(self.filename))
                if grid is not None:
                    ax.grid(grid)
                    
            # Set plot title depending on dataset overlay
            if fig.objCount == 0:
                if title is None:
                    if nChan > 1:
                        title = "Entire Data Timecourse of {} channels".format(nChan)
                    else:
                        title = "Entire Data Timecourse of {}".format(chArr[0])
                ax.set_yticks(fig.tickOffsets)
                ax.set_yticklabels(chArr)
                ax.set_title(title, size=pltConfig["singleTitleSize"])
            else:
                handles, labels = ax.get_legend_handles_labels()
                ax.legend(handles[ : : (nChan + 1)], 
                          labels[ : : (nChan + 1)])
                if title is None:
                    title = overlayTitle.format(len(handles))
                ax.set_title(title, size=pltConfig["singleTitleSize"])

        # Average across trial(s)
        else:

            # Compute trial-average                
            pltArr = np.zeros((tLengths[0], nChan), dtype=self.data.dtype)
            for k, trlno in enumerate(trList):
                idx[timeIdx] = self._selection.time[k]
                pltArr += np.swapaxes(self._get_trial(trlno)[tuple(idx)], timeIdx, 0)
            pltArr /= nTrials

            # If required, compute offsets for multi-channel plot
            if not hasattr(fig, "chanOffsets"):
                fig.chanOffsets = np.cumsum([0] + [np.abs(pltArr).max()] * (nChan - 1))
                fig.tickOffsets = fig.chanOffsets + np.abs(pltArr).mean()

            # Plot the entire trial-averaged array at once
            time = self.time[trList[0]][self._selection.time[0]]
            ax.plot(time, 
                    (pltArr + fig.chanOffsets.reshape(1, nChan)).reshape(time.size, nChan),
                    color=plt.rcParams["axes.prop_cycle"].by_key()["color"][fig.objCount],
                    label=os.path.basename(self.filename))
            if grid is not None:
                ax.grid(grid)
                    
            # Set plot title depending on dataset overlay
            if fig.objCount == 0:
                if title is None:
                    title = "{0} channels {1}across {2} trials".format(nChan, 
                                                                       "averaged " if nTrials > 1 else "",
                                                                       nTrials)
                ax.set_title(title, size=pltConfig["singleTitleSize"])
            else:
                handles, labels = ax.get_legend_handles_labels()
                ax.legend(handles[ : : (nChan + 1)], 
                          labels[ : : (nChan + 1)])
                if title is None:
                    title = overlayTitle.format(len(handles))
                ax.set_title(title, size=pltConfig["singleTitleSize"])
    
    # Increment overlay-counter and draw figure
    fig.objCount += 1
    plt.draw()
    self._selection = None
    return fig


def multipanelplot(self, trials="all", channels="all", toilim=None, avg_channels=False, 
              avg_trials=True, title=None, grid=None, fig=None, **kwargs):
    """
    Plot contents of :class:`~syncopy.AnalogData` objects using multi-panel figure(s)
    
    Please refer to :func:`syncopy.multipanelplot` for detailed usage information. 
    
    Examples
    --------
    Use :func:`~syncopy.tests.misc.generate_artificial_data` to create two synthetic 
    :class:`~syncopy.AnalogData` objects. 
    
    >>> from syncopy.tests.misc import generate_artificial_data
    >>> adata = generate_artificial_data(nTrials=10, nChannels=32) 
    >>> bdata = generate_artificial_data(nTrials=5, nChannels=16) 
    
    Show overview of first 5 channels, averaged across trials 2, 4, and 6:
    
    >>> fig = spy.multipanelplot(adata, channels=range(5), trials=[2, 4, 6])
   
    Overlay last 5 channels, averaged across trials 1, 3, 5: 

    >>> fig = spy.multipanelplot(adata, channels=range(27, 32), trials=[1, 3, 5], fig=fig)
    
    Do not average trials:
    
    >>> fig = spy.multipanelplot(adata, channels=range(27, 32), trials=[1, 3, 5], avg_trials=False)
    
    Plot `adata` and `bdata` simultaneously in two separate figures:
    
    >>> fig1, fig2 = spy.multipanelplot(adata, bdata, channels=range(5), overlay=False)
    
    Overlay `adata` and `bdata`; use channel and trial selections that are valid 
    for both datasets:
    
    >>> fig3 = spy.multipanelplot(adata, bdata, channels=range(5), trials=[1, 2, 3], avg_trials=False)
    
    See also
    --------
    syncopy.multipanelplot : visualize Syncopy data objects using multi-panel plots
    """
    
    # FIXME: maybe summarize this part in a `plotting_parser(...)`?
    if not __plt__:
        raise SPYError(pltErrMsg.format("multipanelplot"))
    
    # Ensure binary flags are in fact binary
    vNames = ["avg_trials", "avg_channels"]
    for k, flag in enumerate([avg_trials, avg_channels]):
        if not isinstance(flag, bool):
            raise SPYTypeError(flag, varname=vNames[k], expected="bool")

    # Pass provided selections on to `Selector` class which performs error 
    # checking and generates required indexing arrays
    self._selection = {"trials": trials, 
                       "channels": channels, 
                       "toilim": toilim}
    
    # Ensure any optional keywords controlling plotting appearance make sense
    if title is not None:
        if not isinstance(title, str):
            raise SPYTypeError(title, varname="title", expected="str")
    if grid is not None:
        if not isinstance(grid, bool):
            raise SPYTypeError(grid, varname="grid", expected="bool")

    # Get trial/channel count ("raw" plotting constitutes a special case)
    if trials is None:
        nTrials = 0
        if toilim is not None:
            lgl = "`trials` to be not `None` to perform timing selection"
            act = "`toilim` was provided but `trials` is `None`"
            raise SPYValueError(legal=lgl, varname="trials/toilim", actual=act)
        if avg_trials:
            msg = "`trials` is `None` but `avg_trials` is `True`. " +\
                "Cannot perform trial averaging without trial specification - " +\
                "setting ``avg_trials = False``. " 
            SPYWarning(msg)
            avg_trials = False
        if avg_channels:
            msg = "Averaging across channels w/o trial specifications results in " +\
                "single-panel plot. Please use `singlepanelplot` instead"
            SPYWarning(msg)
            return
    else:    
        trList = self._selection.trials
        nTrials = len(trList)
    chArr = self.channel[self._selection.channel]
    nChan = chArr.size

    # If we're overlaying, ensure settings match up
    if hasattr(fig, "objCount"):
        if not hasattr(fig, "nTrialPanels") and not hasattr(fig, "nChanPanels"):
            lgl = "overlay-figure generated by `multipanelplot`"
            act = "figure generated by `singlepanelplot`"
            raise SPYValueError(legal=lgl, varname="fig/singlepanelplot", actual=act)
    if hasattr(fig, "nTrialPanels"):
        if nTrials != fig.nTrialPanels:
            lgl = "number of trials to plot matching existing panels in figure"
            act = "{} panels but {} trials for plotting".format(fig.nTrialPanels, 
                                                                nTrials)
            raise SPYValueError(legal=lgl, varname="trials/figure panels", actual=act)
        if avg_trials:
            lgl = "overlay of multi-trial plot"
            act = "trial averaging was requested for multi-trial plot overlay"
            raise SPYValueError(legal=lgl, varname="trials/avg_trials", actual=act)
        if trials is None:
            lgl = "`trials` to be not `None` to append to multi-trial plot"
            act = "multi-trial plot overlay was requested but `trials` is `None`"
            raise SPYValueError(legal=lgl, varname="trials/overlay", actual=act)
        if not avg_channels and not hasattr(fig, "chanOffsets"):
            lgl = "single-channel or channel-averages for appending to multi-trial plot"
            act = "multi-trial multi-channel plot overlay was requested"
            raise SPYValueError(legal=lgl, varname="avg_channels/overlay", actual=act)
    if hasattr(fig, "nChanPanels"):
        if nChan != fig.nChanPanels:
            lgl = "number of channels to plot matching existing panels in figure"
            act = "{} panels but {} channels for plotting".format(fig.nChanPanels, 
                                                                  nChan)
            raise SPYValueError(legal=lgl, varname="channels/figure panels", actual=act)
        if avg_channels:
            lgl = "overlay of multi-channel plot"
            act = "channel averaging was requested for multi-channel plot overlay"
            raise SPYValueError(legal=lgl, varname="channels/avg_channels", actual=act)
        if not avg_trials:
            lgl = "overlay of multi-channel plot"
            act = "mulit-trial plot was requested for multi-channel plot overlay"
            raise SPYValueError(legal=lgl, varname="channels/avg_trials", actual=act)
    if hasattr(fig, "chanOffsets"):
        if avg_channels:
            lgl = "multi-channel plot"
            act = "channel averaging was requested for multi-channel plot overlay"
            raise SPYValueError(legal=lgl, varname="channels/avg_channels", actual=act)
        if nChan != len(fig.chanOffsets):
            lgl = "channel-count matching existing multi-channel panels in figure"
            act = "{} channels per panel but {} channels for plotting".format(len(fig.chanOffsets), 
                                                                              nChan)
            raise SPYValueError(legal=lgl, varname="channels/channels per panel", actual=act)

    # Prepare indexing list respecting potential non-default `dimord`s
    idx = [slice(None), slice(None)]
    chanIdx = self.dimord.index("channel")
    timeIdx = self.dimord.index("time")
    idx[chanIdx] = self._selection.channel
    
    # Generic title for overlay figures
    overlayTitle = "Overlay of {} datasets"

    # Either construct subplot panel layout/vet provided layout or fetch existing
    if fig is None:
        
        # Determine no. of required panels
        if avg_trials and not avg_channels:
            npanels = nChan 
        elif not avg_trials and avg_channels:
            npanels = nTrials
        elif not avg_trials and not avg_channels:
            npanels = int(nTrials == 0) * nChan + nTrials
        else:
            msg = "Averaging across both trials and channels results in " +\
                "single-panel plot. Please use `singlepanelplot` instead"
            SPYWarning(msg)
            return
        
        # Construct subplot panel layout or vet provided layout
        nrow = kwargs.get("nrow", None)
        ncol = kwargs.get("ncol", None)
        nrow, ncol = layout_subplot_panels(npanels, nrow=nrow, ncol=ncol)
        (fig, ax_arr) = plt.subplots(nrow, ncol, constrained_layout=False,
                                     gridspec_kw={"wspace": 0, "hspace": 0.35,
                                                  "left": 0.05, "right": 0.97},
                                     figsize=pltConfig["multiFigSize"],
                                     sharey=True, squeeze=False)

        # Show xlabel only on bottom row of panels
        if nTrials > 0:
            xLabel = "time [s]"
        else:
            xLabel = "samples"
        for col in range(ncol):
            ax_arr[-1, col].set_xlabel(xLabel, size=pltConfig["multiLabelSize"])
            
        # Omit first x-tick in all panels except first panel-row
        for row in range(nrow):
            for col in range(1, ncol):
                ax_arr[row, col].xaxis.get_major_locator().set_params(prune="lower")
                
        # Flatten axis array to make counting a little easier in here and make
        # any surplus panels as unobtrusive as possible
        ax_arr = ax_arr.flatten(order="C")
        for ax in ax_arr:
            ax.tick_params(axis="both", labelsize=pltConfig["multiTickSize"])
            ax.autoscale(enable=True, axis="x", tight=True)
        for k in range(npanels, nrow * ncol):
            ax_arr[k].set_xticks([])
            ax_arr[k].set_yticks([])
            ax_arr[k].set_xlabel("")
            for spine in ax_arr[k].spines.values():
                spine.set_visible(False)
        ax_arr[min(npanels, nrow * ncol - 1)].spines["left"].set_visible(True)
        
        # Monkey-patch object-counter to newly created figure
        fig.objCount = 0

    # Get existing layout
    else:
        ax_arr = fig.get_axes()
        nrow, ncol = ax_arr[0].numRows, ax_arr[0].numCols
        
    # Panels correspond to channels
    if avg_trials and not avg_channels:
        
        # FIXME: Use `TimelockData` to do this?
        
        # Ensure provided timing selection can actually be averaged (leverage 
        # the fact that `toilim` selections exclusively generate slices)
        tLengths = np.zeros((nTrials,), dtype=np.intp)
        for k, tsel in enumerate(self._selection.time):
            start, stop = tsel.start, tsel.stop
            if start is None:
                start = 0
            if stop is None:
                stop = self._get_time([trList[k]], 
                                      toilim=[-np.inf, np.inf])[0].stop
            tLengths[k] = stop - start
            
        # For averaging, all `toilim` selections must be of identical length. 
        # If they aren't close any freshly opened figures and complain appropriately
        if np.unique(tLengths).size > 1:
            if fig.objCount == 0:
                plt.close(fig)
            lgl = "time-selections of equal length for averaging"
            act = "time-selections of varying length"
            raise SPYValueError(legal=lgl, varname="toilim/avg_trials", actual=act)

        # Compute trial-averaged time-courses: 2D array with slice/list
        # selection does not require fancy indexing - no need to check this here
        pltArr = np.zeros((tLengths[0], nChan), dtype=self.data.dtype)
        for k, trlno in enumerate(trList):
            idx[timeIdx] = self._selection.time[k]
            pltArr += np.swapaxes(self._get_trial(trlno)[tuple(idx)], timeIdx, 0)
        pltArr /= nTrials
                
        # Cycle through channels and plot trial-averaged time-courses (time-
        # axis must be identical for all channels, set up `idx` just once)
        idx[timeIdx] = self._selection.time[0]
        time = self.time[trList[k]][self._selection.time[0]]
        for k, chan in enumerate(chArr):
            ax_arr[k].plot(time, pltArr[:, k], label=os.path.basename(self.filename))
            if grid is not None:
                ax_arr[k].grid(grid)
            
        # If we're overlaying datasets, adjust panel- and sup-titles: include
        # legend in top-right axis (note: `ax_arr` is row-major flattened)
        if fig.objCount == 0:
            for k, chan in enumerate(chArr):
                ax_arr[k].set_title(chan, size=pltConfig["multiTitleSize"])
            fig.nChanPanels = nChan
            if title is None:
                if nTrials > 1:
                    title = "Average of {} trials".format(nTrials)
                else:
                    title = "Trial #{}".format(trList[0])
            fig.suptitle(title, size=pltConfig["singleTitleSize"])
        else:
            for k, chan in enumerate(chArr):
                ax_arr[k].set_title("{0}/{1}".format(ax_arr[k].get_title(), chan))
            ax = ax_arr[ncol - 1]
            handles, labels = ax.get_legend_handles_labels()
            ax.legend(handles, labels)
            if title is None:
                title = overlayTitle.format(len(handles))
            fig.suptitle(title, size=pltConfig["singleTitleSize"])
            
    # Panels correspond to trials
    elif not avg_trials and avg_channels:
        
        # Cycle through panels to plot by-trial channel-averages
        for k, trlno in enumerate(trList):
            idx[timeIdx] = self._selection.time[k]
            time = self.time[trList[k]][self._selection.time[k]]
            ax_arr[k].plot(time, 
                           self._get_trial(trlno)[tuple(idx)].mean(axis=chanIdx).squeeze(),
                           label=os.path.basename(self.filename))
            if grid is not None:
                ax_arr[k].grid(grid)

        # If we're overlaying datasets, adjust panel- and sup-titles: include
        # legend in top-right axis (note: `ax_arr` is row-major flattened)
        if fig.objCount == 0:
            for k, trlno in enumerate(trList):
                ax_arr[k].set_title("Trial #{}".format(trlno), size=pltConfig["multiTitleSize"])
            fig.nTrialPanels = nTrials
            if title is None:
                if nChan > 1:
                    title = "Average of {} channels".format(nChan)
                else:
                    title = chArr[0]
            fig.suptitle(title, size=pltConfig["singleTitleSize"])
        else:
            for k, trlno in enumerate(trList):
                ax_arr[k].set_title("{0}/#{1}".format(ax_arr[k].get_title(), trlno))
            ax = ax_arr[ncol - 1]
            handles, labels = ax.get_legend_handles_labels()
            ax.legend(handles, labels)
            if title is None:
                title = overlayTitle.format(len(handles))
            fig.suptitle(title, size=pltConfig["singleTitleSize"])

    # Panels correspond to channels (if `trials` is `None`) otherwise trials
    elif not avg_trials and not avg_channels:
        
        # Plot each channel in separate panel
        if nTrials == 0:
            chanSec = np.arange(self.channel.size)[self._selection.channel]
            for k, chan in enumerate(chanSec):
                idx[chanIdx] = chan
                ax_arr[k].plot(self.data[tuple(idx)].squeeze(),
                               label=os.path.basename(self.filename))
                if grid is not None:
                    ax_arr[k].grid(grid)
                    
            # If we're overlaying datasets, adjust panel- and sup-titles: include
            # legend in top-right axis (note: `ax_arr` is row-major flattened)
            if fig.objCount == 0:
                for k, chan in enumerate(chArr):
                    ax_arr[k].set_title(chan, size=pltConfig["multiTitleSize"])
                fig.nChanPanels = nChan
                if title is None:
                    title = "Entire Data Timecourse"
                fig.suptitle(title, size=pltConfig["singleTitleSize"])
            else:
                for k, chan in enumerate(chArr):
                    ax_arr[k].set_title("{0}/{1}".format(ax_arr[k].get_title(), chan))
                ax = ax_arr[ncol - 1]
                handles, labels = ax.get_legend_handles_labels()
                ax.legend(handles, labels)
                if title is None:
                    title = overlayTitle.format(len(handles))
                fig.suptitle(title, size=pltConfig["singleTitleSize"])
        
        # Each trial gets its own panel w/multiple channels per panel
        else:

            # If required, compute max amplitude across provided trials + channels
            if not hasattr(fig, "chanOffsets"):
                maxAmps = np.zeros((nTrials,), dtype=self.data.dtype)
                tickOffsets = maxAmps.copy()
                for k, trlno in enumerate(trList):
                    idx[timeIdx] = self._selection.time[k]
                    pltArr = np.abs(self._get_trial(trlno)[tuple(idx)])
                    maxAmps[k] = pltArr.max()
                    tickOffsets[k] = pltArr.mean()
                fig.chanOffsets = np.cumsum([0] + [maxAmps.max()] * (nChan - 1))
                fig.tickOffsets = fig.chanOffsets + tickOffsets.mean()
            
            # Cycle through panels to plot by-trial multi-channel time-courses
            for k, trlno in enumerate(trList):
                idx[timeIdx] = self._selection.time[k]
                time = self.time[trList[k]][self._selection.time[k]]
                pltArr = np.swapaxes(self._get_trial(trlno)[tuple(idx)], timeIdx, 0)
                ax_arr[k].plot(time, 
                               (pltArr + fig.chanOffsets.reshape(1, nChan)).reshape(time.size, nChan), 
                               color=plt.rcParams["axes.prop_cycle"].by_key()["color"][fig.objCount],
                               label=os.path.basename(self.filename))
                if grid is not None:
                    ax_arr[k].grid(grid)

            # If we're overlaying datasets, adjust panel- and sup-titles: include
            # legend in top-right axis (note: `ax_arr` is row-major flattened)
            # Note: y-axis is shared across panels, so `yticks` need only be set once
            if fig.objCount == 0:
                for k, trlno in enumerate(trList):
                    ax_arr[k].set_title("Trial #{}".format(trlno), size=pltConfig["multiTitleSize"])
                ax_arr[0].set_yticks(fig.tickOffsets)
                ax_arr[0].set_yticklabels(chArr)
                for i in range(k + 1, nrow * ncol):
                    ax_arr[i].tick_params(axis="both", length=0, width=0)
                fig.nTrialPanels = nTrials
                if title is None:
                    if nChan > 1:
                        title = "{} channels".format(nChan)
                    else:
                        title = chArr[0]
                fig.suptitle(title, size=pltConfig["singleTitleSize"])
            else:
                for k, trlno in enumerate(trList):
                    ax_arr[k].set_title("{0}/#{1}".format(ax_arr[k].get_title(), trlno))
                ax_arr[0].set_yticklabels([" "] * chArr.size)
                ax = ax_arr[ncol - 1]
                handles, labels = ax.get_legend_handles_labels()
                ax.legend(handles[ : : (nChan + 1)], 
                          labels[ : : (nChan + 1)])
                if title is None:
                    title = overlayTitle.format(len(handles))
                fig.suptitle(title, size=pltConfig["singleTitleSize"])
    
    # Increment overlay-counter, draw figure and wipe data-selection slot
    fig.objCount += 1
    plt.draw()
    self._selection = None
    return fig
