graph LR
    classDef MEM fill:#ff908a,stroke:#333,stroke-width:2px;
    classDef DISC fill:#78e4ff,stroke:#333,stroke-width:1px;
    classDef default fill:#9cfcff,stroke:#333,stroke-width:1px;
    
    spyRead[/.spy\] -->|load| Data
    FTread[/.mat\] -->|load_ft_raw| Data
    NWBread[/nwb\] -->|load_nwd| Data
    npInput[NumPy arrays] -.->|collect_trials| Data(AnalogData)
        
    Data -->|connectivityanalysis| CData(CrossSpectralData)
    Data -.-> |singlepanelplot|PlotD1[Figures]
    Data -.-> |show| ShowD1[NumPy arrays]
    
    CData -.-> |singlepanelplot|PlotD[Figures]
    CData -.-> |show| ShowD2[NumPy arrays]
    CData --> |save| SaveD2[/.spy\]
    class npInput,PlotD,ShowD1,PlotD1,ShowD2,PlotD2 MEM;
    class Data,CData DISC;
    linkStyle 4 stroke:#78e4ff,stroke-width:3px;
